### ISSUE TITLE
[DOCS]  Memory leak on documentation website casuing website to crash

### ISSUE THREAD

**Issue by tomsq** [harlan-zw/nuxt-seo#213]
### Describe the bug

Maximum call stack size exceeded in logged in the console:

<img width="480" alt="image" src="https://github.com/harlan-zw/nuxt-seo/assets/25229106/2e730a6d-2cc8-4826-879c-f625206f7942">

### Reproduction

Visit https://nuxtseo.com

### System / Nuxt Info

```Shell
MacOS

Google Chrome
Version 123.0.6312.58 (Official Build) (arm64)
```

**Comment by harlan-zw** [comment]
Thanks for flagging this, not entirely sure what caused this but clearing the lock file solved it.

The docs site will have more issues than other sites for sure, this is because it's updated very regularly, getting deployed when I push to main so they aren't tested. 

Testing for CSS issues and a memory leak like this is difficult, all of the other pages seemed to work fine, just an issue with the home page.
