### ISSUE TITLE
Using updateSiteConfig in Nuxt3 Server Plugins reports an error

### ISSUE THREAD

**Issue by WooHoo-Wu** [harlan-zw/nuxt-seo#268]
### Describe the bug

[nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'siteConfig')
    at updateSiteConfig (file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/chunks/runtime.mjs:7360:36)
    at file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/chunks/runtime.mjs:7624:3
    at createNitroApp (file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/chunks/runtime.mjs:12876:7)
    at file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/chunks/runtime.mjs:12884:18
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

### System / Nuxt Info

```Shell
export default defineNitroPlugin(async (nitroApp) => {
    // nitroApp.hooks.hook('site-config:init', ({ event, siteConfig }) => {
    //     siteConfig.push({
    //         url: 'https://www-dev.xmp.one/',
    //     });
    //     console.log(siteConfig);
    // });
    updateSiteConfig({
        url: 'https://www-dev.xmp.one/',
    });
});
```

**Comment by harlan-zw** [comment]
Hi, you may be confusing the Nuxt API with the Nitro API, you need to follow [Nitro - updateSiteConfig](https://nuxtseo.com/site-config/nitro-api/update-site-config) - the only difference is you need to provide the event as the first argument.

You should only really be using these functions if you have a dynamic site URL such as multi-tenancy app or multi-domains with i18n. Otherwise you can just set `site.url` in your Nuxt config.

**Comment by RobArkesteijn** [comment]
@harlan-zw 
I am using multi domains with i18n, which is why I am using this strategy.

```
import { parse } from 'tldts'

export default defineNitroPlugin(async (nitroApp) => {
  const locales = {
    uk: import.meta.env.DOMAIN_UK as string,
    nl: import.meta.env.DOMAIN_NL as string,
    es: import.meta.env.DOMAIN_ES as string,
    fr: import.meta.env.DOMAIN_FR as string,
    it: import.meta.env.DOMAIN_IT as string,
  }

  nitroApp.hooks.hook('site-config:init', ({ event, siteConfig }) => {
    const host = useNitroOrigin(event)

    const parsed = parse(host)
    const tld = parsed.publicSuffix

    if (tld && !import.meta.dev) {
      siteConfig.push({
        url: locales[tld as keyof typeof locales],
      })
    }
    else {
      // Set default url based on default locale (UK)
      siteConfig.push({
        url: import.meta.env.DOMAIN_UK || 'http://domain-uk.local:3000',
      })
    }
  })
})
```
This seems to work, but now I am still getting the `Your i18n baseUrl [object Object] doesn't match your site url. This can lead to unexpected behavior. Please set a matching baseUrl in your i18n config.` warning. Is this supposed to happen?
I do not even have a baseUrl set... on purpose. The baseUrl can not be dynamic right? So how can it match my site url in this case?

**Comment by RobArkesteijn** [comment]
@harlan-zw Sorry, but I think this was because of caching, I do not have the issue anymore. It seems to work fine now, thanks
