### ISSUE TITLE
Cannot deploy to cloudflare pages when using @nuxtjs/seo and @nuxt/content

### ISSUE THREAD

**Issue by Daandeve** [harlan-zw/nuxt-seo#344]
### Describe the bug

When I try to deploy my app to cloudflare pages I get the following run error:
```
Failed to read robot rules from content files. Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler.
```

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.11
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/partytown@1.5.0, @nuxtjs/google-fonts@3.2.0, @nuxtjs/fontaine@0.4.3, @nuxtjs/i18n@8.5.5, @nuxtjs/seo@2.0.0-rc.23, @nuxtjs/tailwindcss@6.12.2, @pinia/nuxt@0.5.5, @pinia-plugin-persistedstate/nuxt@1.2.1, @nuxt/content@2.13.4, @nuxt/image@1.8.1, @tresjs/nuxt@3.0.7, v-plausible@1.2.0, nuxt-booster@3.1.6
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hi, thanks for flagging this. It looks like the Nuxt Robots module can't support Nuxt Content in Cloudflare without a bit more work.

For the time being the module will now disable the integration with a warning, to silence the warning you can set `robots: { disableNuxtContentIntegration: true }` in your Nuxt config.

**Comment by grapelaw** [comment]
@harlan-zw I'm really happy to see similar issue here but even I use only nuxt/seo not nuxt/content I get similar issue while deploying on cloudflare as `Failed to publish your Function. Got error: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/` because of sitemap configuration. If you have any idea, please let me now thanks in advance :)

**Comment by Zisan-uzum** [comment]
@harlan-zw Hi, I get similar issue while deploying on Cloudflare even I just use nuxt/seo  not nuxt/content as 

`Failed to publish your Function. Got error: Uncaught Error: Disallowed operation called within global scope. Asynchronous I/O (ex: fetch() or connect()), setting a timeout, and generating random values are not allowed within global scope. To fix this error, perform this operation within a handler. https://developers.cloudflare.com/workers/runtime-apis/handlers/`.


 Seo sitemap configuration apparently causes error how can i solve do you have any idea thanks in advance :)
