### ISSUE TITLE
help: LocalBusiness with multiple locations

### ISSUE THREAD

**Issue by shurth** [harlan-zw/nuxt-seo#366]
### 📚 What are you trying to do?

I could just be missing it, but I don't see the "department" attribute on Organization / LocalBusiness. From what I can tell, when you have a business with multiple locations, the best practice is to put each one in a "department" array on Organization - is this something the library supports?

**Comment by shurth** [comment]
Scratch this. It may not be in the typescript defs, but just adding "department" and a list of "defineLocalBusiness" seems to work. Thanks for the library!

**Comment by harlan-zw** [comment]
Hi @shurth, thanks for the issue. 

Let me just clarify, Nuxt Schema.org only provides types for keys which Google recommends as part of their [Structured Data docs](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data). This is to improve type performance otherwise it would be very slow.

You can provide any value on top of this.
